---
apt_recovery_lock_retries: 36
apt_recovery_lock_delay: 5
apt_recovery_lock_paths:
  - /var/lib/dpkg/lock-frontend
  - /var/lib/dpkg/lock
  - /var/lib/apt/lists/lock
  - /var/cache/apt/archives/lock
