---
qdrant_docker_image: "qdrant/qdrant:v1.17.0"
qdrant_docker_container_name: qdrant
qdrant_docker_data_dir: /opt/qdrant
qdrant_docker_api_key: >-
  {{ bao_local_llm_secrets.QDRANT_API_KEY | default(lookup('env', 'QDRANT_API_KEY'), true) }}
qdrant_docker_storage_driver: "fuse-overlayfs"
