---
qdrant_docker_image: "qdrant/qdrant:v1.18.2"
qdrant_docker_container_name: qdrant
qdrant_docker_data_dir: /opt/qdrant
qdrant_docker_api_key: "{{ lookup('env', 'QDRANT_API_KEY') }}"
qdrant_docker_storage_driver: "fuse-overlayfs"
