"""Pytest fixtures for E2E pipeline tests."""

from dataclasses import dataclass
import json
import os
from pathlib import Path

import pytest


class SecretValue:
    """String-like secret value with a redacted repr for pytest tracebacks."""

    def __init__(self, value):
        self._value = value

    def __str__(self):
        return self._value

    def __repr__(self):
        return "<redacted>"

    def __format__(self, spec):
        return format(self._value, spec)


@dataclass(frozen=True)
class SplunkCredentials:
    """Splunk credentials with redacted secret representation."""

    mgmt_url: str
    user: str
    password: SecretValue

    def __iter__(self):
        yield self.mgmt_url
        yield self.user
        yield self.password

    def __repr__(self):
        return (
            "SplunkCredentials("
            f"mgmt_url={self.mgmt_url!r}, user={self.user!r}, password=<redacted>)"
        )


def _inventory_path():
    return Path(__file__).resolve().parents[2] / "inventory" / "tofu_inventory.json"


def _cribl_ips(containers, role_tag):
    """IPs of Cribl containers carrying role_tag ('edge' or 'stream').

    Matches the predicate used in inventory/load_tofu.yml.
    """
    return [
        info["ip"]
        for info in containers.values()
        if role_tag in info.get("tags", []) and "cribl" in info.get("tags", [])
    ]


def pytest_generate_tests(metafunc):
    """Parametrize per-Edge tests at collection time.

    Tests taking an ``edge_ip`` argument run once per Cribl Edge LXC so a
    failure on one Edge is reported independently of the others. With no
    inventory file the parameter set is empty and the tests are skipped.
    """
    if "edge_ip" in metafunc.fixturenames:
        containers = {}
        if _inventory_path().exists():
            with open(_inventory_path()) as f:
                containers = json.load(f).get("containers", {})
        metafunc.parametrize("edge_ip", _cribl_ips(containers, "edge"))


@pytest.fixture(scope="session")
def tofu_inventory():
    """Load tofu inventory from JSON file.

    Returns the full inventory dict from inventory/tofu_inventory.json.
    The file is generated by terraform-proxmox and must exist before running
    E2E tests.
    """
    inventory_path = _inventory_path()
    if not inventory_path.exists():
        pytest.skip(
            f"OpenTofu inventory not found at {inventory_path}. "
            "Generate it with: cd ~/git/terraform-proxmox/main && "
            "terragrunt output -json ansible_inventory > "
            "~/git/ansible-proxmox-apps/main/inventory/tofu_inventory.json"
        )
    with open(inventory_path) as f:
        return json.load(f)


@pytest.fixture(scope="session")
def constants(tofu_inventory):
    """Return the constants dict from tofu inventory.

    Contains service_ports, syslog_ports, netflow_ports, and
    notification_ports as defined in terraform-proxmox locals.tf.
    """
    if "constants" not in tofu_inventory:
        pytest.skip("Inventory missing 'constants' section")
    return tofu_inventory["constants"]


@pytest.fixture(scope="session")
def haproxy_host(tofu_inventory):
    """Return the HAProxy container IP from inventory."""
    return tofu_inventory["containers"]["haproxy"]["ip"]


@pytest.fixture(scope="session")
def cribl_edge_ips(tofu_inventory):
    """Return list of Cribl Edge LXC IPs from inventory.

    Discovers Edge containers by matching both 'edge' and 'cribl' tags
    in the containers section of the tofu inventory, matching the
    predicate used in inventory/load_tofu.yml.
    """
    ips = _cribl_ips(tofu_inventory.get("containers", {}), "edge")
    if not ips:
        pytest.skip("No Cribl Edge LXC containers found in inventory")
    return ips


@pytest.fixture(scope="session")
def cribl_stream_ips(tofu_inventory):
    """Return list of Cribl Stream LXC IPs from inventory.

    Discovers Stream containers by matching both 'stream' and 'cribl' tags
    in the containers section of the tofu inventory, matching the
    predicate used in inventory/load_tofu.yml.
    """
    ips = _cribl_ips(tofu_inventory.get("containers", {}), "stream")
    if not ips:
        pytest.skip("No Cribl Stream LXC containers found in inventory")
    return ips


@pytest.fixture(scope="session")
def splunk_host(tofu_inventory):
    """Return the Splunk VM IP from inventory."""
    return tofu_inventory["splunk_vm"]["splunk"]["ip"]


@pytest.fixture(scope="session")
def splunk_creds(tofu_inventory, constants):
    """Return Splunk credentials as (mgmt_url, user, password).

    The management URL is built from the Splunk VM IP and the splunk_mgmt
    port in tofu constants. The password comes from the SPLUNK_PASSWORD
    environment variable.
    """
    splunk_ip = tofu_inventory["splunk_vm"]["splunk"]["ip"]
    mgmt_port = constants["service_ports"]["splunk_mgmt"]
    raw_password = os.environ.get("SPLUNK_PASSWORD")
    if not raw_password:
        pytest.skip("SPLUNK_PASSWORD environment variable not set")
    mgmt_url = os.environ.get("SPLUNK_MGMT_URL", f"https://{splunk_ip}:{mgmt_port}")
    return SplunkCredentials(mgmt_url, "admin", SecretValue(raw_password))


@pytest.fixture(scope="session")
def splunk_hec_url(splunk_host, constants):
    """Return the Splunk HEC base URL."""
    port = constants["service_ports"]["splunk_hec"]
    return os.environ.get("SPLUNK_HEC_URL", f"https://{splunk_host}:{port}")


@pytest.fixture(scope="session")
def splunk_hec_token():
    """Return the Splunk HEC token from the environment."""
    raw_token = os.environ.get("SPLUNK_HEC_TOKEN")
    if not raw_token:
        pytest.skip("SPLUNK_HEC_TOKEN environment variable not set")
    return SecretValue(raw_token)


@pytest.fixture(scope="session")
def pipeline_poll_timeout():
    """Return the live-pipeline poll timeout in seconds."""
    return int(os.environ.get("PIPELINE_POLL_TIMEOUT_SECONDS", "120"))


@pytest.fixture(scope="session")
def pipeline_poll_interval():
    """Return the live-pipeline poll interval in seconds."""
    return int(os.environ.get("PIPELINE_POLL_INTERVAL_SECONDS", "10"))
