---
alert_delivery_channels_enabled: false
alert_delivery_channels_token: ""
alert_delivery_channels_api_url: https://slack.com/api
alert_delivery_channels_general_name: homelab-alerts
alert_delivery_channels_critical_name: homelab-alerts-critical
alert_delivery_channels_general_id: ""
alert_delivery_channels_critical_id: ""
