---
ntfy_docker_image: "binwiederhier/ntfy:v2.26.0"
ntfy_docker_container_name: ntfy
ntfy_docker_http_port: 8080
ntfy_docker_data_dir: /opt/ntfy
ntfy_docker_cache_duration: "12h"
ntfy_docker_attachment_cache_dir: /var/cache/ntfy/attachments
