---
openbao_hermes_private_agent_approles: >-
  {{ ([{'name': openbao_hermes_private_agent_approle_name,
        'policy': openbao_hermes_private_agent_policy_name,
        'secret_id_num_uses': openbao_approle_secret_id_num_uses,
        'token_ttl': openbao_approle_token_ttl,
        'token_max_ttl': openbao_approle_token_max_ttl,
        'secret_id_bound_cidrs': openbao_hermes_private_agent_secret_id_cidr,
        'manage_secret_id': false}]
     if openbao_hermes_private_agent_secret_id_cidr | length > 0 else []) }}
