---
# ntfy Docker handlers

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart ntfy
  community.docker.docker_compose_v2:
    project_src: "{{ ntfy_docker_data_dir }}"
    state: present
    recreate: always

- name: Restart ntfy-to-slack instances
  ansible.builtin.systemd:
    name: "ntfy-to-slack@{{ item.key }}.service"
    state: restarted
    daemon_reload: true
  loop: "{{ ntfy_docker_slack_active_routes | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Restart ntfy subscriber
  ansible.builtin.systemd:
    name: ntfy-subscribe.service
    state: restarted
    daemon_reload: true
