---
- name: Create Secondary DNS zone
  delegate_to: localhost
  ansible.builtin.uri:
    url: "{{ technitium_dns_api_url }}/api/zones/create?token={{ technitium_dns_api_token }}"
    method: POST
    body_format: form-urlencoded
    body:
      zone: "{{ technitium_dns_zone }}"
      type: "Secondary"
      primaryNameServerAddresses: "{{ technitium_dns_primary_ip }}"
      zoneTransferProtocol: "{{ technitium_dns_zone_transfer_protocol }}"
    return_content: true
    timeout: "{{ technitium_dns_api_timeout }}"
    status_code: [200, 400]
  register: technitium_dns_secondary_zone_create
  changed_when: technitium_dns_secondary_zone_create.json.status == "ok"
  when:
    - technitium_dns_role == 'secondary'
    - technitium_dns_apply | bool
    - technitium_dns_zone not in technitium_dns_existing_zones
  no_log: true
