---
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart sortarr
  community.docker.docker_compose_v2:
    project_src: "{{ sortarr_data_dir }}"
    state: present
    recreate: always
