---
workstation_connections_profile: "{{ tofu_data.workstation_connections.proxman }}"
workstation_connections_addr: "{{ lookup('env', 'BAO_ADDR') | default('', true) }}"
workstation_connections_token: "{{ lookup('env', 'BAO_TOKEN') | default('', true) }}"
