---
- name: Restart immich
  community.docker.docker_compose_v2:
    project_src: "{{ immich_data_dir }}"
    state: restarted
  vars:
    ansible_python_interpreter: /opt/ansible-venv/bin/python
  when: immich_manage_services | bool
