---
# prometheus_pve_exporter role handlers

- name: Restart pve-exporter
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_pve_exporter_data_dir }}"
    state: present
    recreate: always
