---
- name: Download the Docker Engine default seccomp profile
  ansible.builtin.uri:
    url: >-
      {{ github_runner_container_seccomp_default_profile
         | format(github_runner_container_seccomp_profile_release) }}
    return_content: true
  register: github_runner_container_seccomp_profile_download

- name: Validate the downloaded seccomp profile
  ansible.builtin.include_tasks: seccomp_default_profile_validate.yml
  vars:
    github_runner_container_seccomp_default_profile_content: >-
      {{ github_runner_container_seccomp_profile_download.content }}
