---
name: Cancel on close
on:
  pull_request:
    types: [closed]
permissions: {}
jobs:
  cancel-on-close:
    permissions:
      actions: write
    uses: dryvist/.github/.github/workflows/_cancel-on-close.yml@6a0ffc17fe67dfad4c5d2541cdf630f2e2376991 # v1.11.1
