---
name: Copilot Setup Steps

on:
  workflow_call:

jobs:
  copilot-setup-steps:
    name: Copilot Setup Steps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install ansible tools
        run: pip install ansible-core ansible-lint
